package com.opipo.ultimategamesrating.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

@DisplayName("Company autogenerated")
public class CompanyTest {

    private Company company;

    @BeforeEach
    public void init() {
        company = new Company();
    }


    @Test
    @DisplayName("The getter and the setter of name work well")
    public void nameAttributeTest() {
        String name = Integer.toString(1);
        company.setName(name);
        assertEquals(name, company.getName());
    }


    @Test
    public void givenSameObjReturnThatTheyAreEquals() {
        Company o1 = new Company();
        Company o2 = new Company();
        assertEquals(o1, o2);
    }

    @Test
    public void givenSameObjReturnZero() {
        Company o1 = new Company();
        Company o2 = new Company();
        assertEquals(0, o1.compareTo(o2));
    }

    @Test
    public void givenObjectFromOtherClassReturnThatTheyArentEquals() {
        Company o1 = new Company();
        assertNotEquals(o1, new String());
    }

    @Test
    public void givenSameObjReturnSameHashCode() {
        Company o1 = new Company();
        Company o2 = new Company();
        assertEquals(o1.hashCode(), o2.hashCode());
    }

}