package com.opipo.ultimategamesrating.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

@DisplayName("Platform autogenerated")
public class PlatformTest {

    private  Platform platform;

    @BeforeEach
    public void init(){
        platform = new Platform();
    }



    @Test
    @DisplayName("The getter and the setter of id work well")
    public void idAttributeTest(){
        String id = Integer.toString(1);
        platform.setId(id);
        assertEquals(id,platform.getId());
    }


    @Test
    @DisplayName("The getter and the setter of name work well")
    public void nameAttributeTest(){
        String name = Integer.toString(2);
        platform.setName(name);
        assertEquals(name,platform.getName());
    }


    @Test
    @DisplayName("The getter and the setter of generation work well")
    public void generationAttributeTest(){
        String generation = Integer.toString(3);
        platform.setGeneration(generation);
        assertEquals(generation,platform.getGeneration());
    }



    @Test
    public void givenSameObjReturnThatTheyAreEquals(){
        Platform o1 = new Platform();
        Platform o2 = new Platform();
        assertEquals(o1, o2);
    }

    @Test
    public void givenSameObjReturnZero(){
        Platform o1 = new Platform();
        Platform o2 = new Platform();
        assertEquals(0, o1.compareTo(o2));
    }

    @Test
    public void givenObjectFromOtherClassReturnThatTheyArentEquals(){
        Platform o1 = new Platform();
        assertNotEquals(o1, new String());
    }

    @Test
    public void givenSameObjReturnSameHashCode(){
        Platform o1 = new Platform();
        Platform o2 = new Platform();
        assertEquals(o1.hashCode(), o2.hashCode());
    }

}