package com.opipo.ultimategamesrating.model;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

@DisplayName("Sequence autogenerated")
public class SequenceTest {

	private Sequence sequence;

	@BeforeEach
	public void init() {
		sequence = new Sequence();
	}

	@Test
	@DisplayName("The getter and the setter of id work well")
	public void idAttributeTest() {
		String id = Integer.toString(1);
		sequence.setId(id);
		assertEquals(id, sequence.getId());
	}

	@Test
	@DisplayName("The getter and the setter of seq work well")
	public void seqAttributeTest() {
		Integer seq = Integer.valueOf(2);
		sequence.setSeq(seq);
		assertEquals(seq, sequence.getSeq());
	}

	@Test
	public void givenSameObjReturnThatTheyAreEquals() {
		Sequence o1 = new Sequence();
		Sequence o2 = new Sequence();
		assertEquals(o1, o2);
	}

	@Test
	public void givenSameObjReturnZero() {
		Sequence o1 = new Sequence();
		Sequence o2 = new Sequence();
		assertEquals(0, o1.compareTo(o2));
	}

	@Test
	public void givenObjectFromOtherClassReturnThatTheyArentEquals() {
		Sequence o1 = new Sequence();
		assertNotEquals(o1, new String());
	}

	@Test
	public void givenSameObjReturnSameHashCode() {
		Sequence o1 = new Sequence();
		Sequence o2 = new Sequence();
		assertEquals(o1.hashCode(), o2.hashCode());
	}

}