package com.opipo.ultimategamesrating.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

@DisplayName("Videogame autogenerated")
public class VideogameTest {

    private Videogame videogame;

    @BeforeEach
    public void init() {
        videogame = new Videogame();
    }


    @Test
    @DisplayName("The getter and the setter of name work well")
    public void nameAttributeTest() {
        String name = Integer.toString(1);
        videogame.setName(name);
        assertEquals(name, videogame.getName());
    }


    @Test
    public void givenSameObjReturnThatTheyAreEquals() {
        Videogame o1 = new Videogame();
        Videogame o2 = new Videogame();
        assertEquals(o1, o2);
    }

    @Test
    public void givenSameObjReturnZero() {
        Videogame o1 = new Videogame();
        Videogame o2 = new Videogame();
        assertEquals(0, o1.compareTo(o2));
    }

    @Test
    public void givenObjectFromOtherClassReturnThatTheyArentEquals() {
        Videogame o1 = new Videogame();
        assertNotEquals(o1, new String());
    }

    @Test
    public void givenSameObjReturnSameHashCode() {
        Videogame o1 = new Videogame();
        Videogame o2 = new Videogame();
        assertEquals(o1.hashCode(), o2.hashCode());
    }

}